name: Documentation

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main
      - master
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: julia-actions/setup-julia@latest
        with:
          version: '1' # gebruik Julia 1.x, of zet '1.10' voor specifieke versie

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.instantiate();
          '

      - name: Build and deploy documentation
        run: |
          julia --project=docs docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
